/**
 * Copyright © 2018 spring-data-dynamodb (https://github.com/prasanna0586/spring-data-dynamodb)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.socialsignin.spring.data.dynamodb.domain.sample;

import org.socialsignin.spring.data.dynamodb.annotation.DynamoDBAutoGeneratedKey;
import org.springframework.data.annotation.*;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.util.Date;

/**
 * Domain class for auditing functionality testing.
 *
 * SDK v2 Migration Notes:
 * - SDK v1: @DynamoDBTable → SDK v2: @DynamoDbBean (table name resolved at runtime)
 * - SDK v1: @DynamoDBHashKey → SDK v2: @DynamoDbPartitionKey
 * - SDK v1: @DynamoDBAutoGeneratedKey → SDK v2: @DynamoDBAutoGeneratedKey (custom annotation in SDK_V1_COMPATIBLE mode)
 * - Spring Data auditing annotations (@CreatedBy, @CreatedDate, @LastModifiedBy, @LastModifiedDate) remain unchanged
 * - Auditing works the same way in SDK v2 as it did in SDK v1
 * @author Prasanna Kumar Ramachandran
 */
@DynamoDbBean
public class AuditableUser {

    @Id
    private String id;

    private String firstname;

    @CreatedBy
    private String createdBy;

    @CreatedDate
    private Date createdAt;

    @LastModifiedBy
    private String lastModifiedBy;

    @LastModifiedDate
    private Date lastModifiedAt;

    @Version
    private Long version;

    public AuditableUser() {
    }

    public AuditableUser(String firstName) {
        this.firstname = firstName;
    }

    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstName) {
        this.firstname = firstName;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy(org.socialsignin.spring.data.dynamodb.marshaller.Date2IsoAttributeConverter.class)
    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    @software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy(org.socialsignin.spring.data.dynamodb.marshaller.Date2IsoAttributeConverter.class)
    public Date getLastModifiedAt() {
        return lastModifiedAt;
    }

    public void setLastModifiedAt(Date lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}
