/**
 * Copyright © 2018 spring-data-dynamodb (https://github.com/prasanna0586/spring-data-dynamodb)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.socialsignin.spring.data.dynamodb.domain.sample;

import org.socialsignin.spring.data.dynamodb.annotation.DynamoDBAutoGeneratedKey;
import org.springframework.data.annotation.Id;
import software.amazon.awssdk.enhanced.dynamodb.AttributeConverter;
import software.amazon.awssdk.enhanced.dynamodb.AttributeValueType;
import software.amazon.awssdk.enhanced.dynamodb.EnhancedType;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

import java.time.LocalDateTime;

/**
 * SDK v2 Migration Notes:
 * - SDK v1: @DynamoDBTable → SDK v2: @DynamoDbBean (table name resolved at runtime)
 * - SDK v1: @DynamoDBHashKey → SDK v2: @DynamoDbPartitionKey
 * - SDK v1: @DynamoDBAutoGeneratedKey → SDK v2: @DynamoDBAutoGeneratedKey (custom annotation in SDK_V1_COMPATIBLE mode)
 * - SDK v1: @DynamoDBIndexHashKey → SDK v2: @DynamoDbSecondaryPartitionKey
 * - SDK v1: @DynamoDBIndexRangeKey → SDK v2: @DynamoDbSecondarySortKey
 * - SDK v1: @DynamoDBTypeConverted → SDK v2: @DynamoDbConvertedBy
 * - SDK v1: DynamoDBTypeConverter → SDK v2: AttributeConverter
 * - SDK v2: AttributeConverter uses AttributeValue instead of target type for conversion
 */
@DynamoDbBean
public class Feed {
    @Id
    private String idx;
    private int userIdx;
    private String message;
    private int paymentType;
    private LocalDateTime regDate;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("idx")
    @DynamoDBAutoGeneratedKey
    public String getIdx() {
        return idx;
    }

    @DynamoDbAttribute("userIdx")
    public int getUserIdx() {
        return userIdx;
    }

    @DynamoDbAttribute("message")
    @DynamoDbSecondaryPartitionKey(indexNames = "aaa")
    public String getMessage() {
        return message;
    }

    // @DynamoDbSecondarySortKey(indexNames = "aaa", attributeName = "PaymentType")
    @DynamoDbAttribute("paymentType")
    public int getPaymentType() {
        return paymentType;
    }

    @DynamoDbConvertedBy(LocalDateTimeConverter.class)
    @DynamoDbAttribute("regDate")
    @DynamoDbSecondarySortKey(indexNames = "aaa")
    public LocalDateTime getRegDate() {
        return regDate;
    }

    public void setIdx(String idx) {
        this.idx = idx;
    }

    public void setUserIdx(int userIdx) {
        this.userIdx = userIdx;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void setPaymentType(int paymentType) {
        this.paymentType = paymentType;
    }

    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * SDK v2 AttributeConverter for LocalDateTime.
     * Converts LocalDateTime to/from String representation in DynamoDB.
     */
    static public class LocalDateTimeConverter implements AttributeConverter<LocalDateTime> {

        @Override
        public AttributeValue transformFrom(LocalDateTime time) {
            return AttributeValue.builder().s(time.toString()).build();
        }

        @Override
        public LocalDateTime transformTo(AttributeValue attributeValue) {
            return LocalDateTime.parse(attributeValue.s());
        }

        @Override
        public EnhancedType<LocalDateTime> type() {
            return EnhancedType.of(LocalDateTime.class);
        }

        @Override
        public AttributeValueType attributeValueType() {
            return AttributeValueType.S;
        }
    }
}
