/**
 * Copyright © 2018 spring-data-dynamodb (https://github.com/prasanna0586/spring-data-dynamodb)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.socialsignin.spring.data.dynamodb.domain.sample;

import org.socialsignin.spring.data.dynamodb.annotation.DynamoDBAutoGeneratedKey;
import org.socialsignin.spring.data.dynamodb.marshaller.BooleanNumberAttributeConverter;
import org.springframework.data.annotation.Id;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;

import java.util.Date;

/**
 * Entity demonstrating:
 * - Auto-generated partition key
 * - Global Secondary Index (GSI) with custom partition and sort keys
 * - Boolean stored as Number (N) type for backward compatibility
 * - Date attribute handling
 *
 * GSI: idx_global_usrNo_feedOpenYn
 * - Partition key: usrNo (Number)
 * - Sort key: feedOpenYn (Boolean stored as Number - "0" or "1")
 *
 * SDK v2 Migration Notes:
 * - Boolean as GSI sort key requires custom converter to Number type
 * - SDK v1 @DynamoDBTyped → SDK v2 @DynamoDbConvertedBy
 * - Date is handled natively by SDK v2 (stored as epoch milliseconds by default)
 */
@DynamoDbBean
public class FeedUser {
    @Id
    private String id;

    private int usrNo;
    private String feedId;
    private Date feedRegDate;
    private boolean feedOpenYn;

    /**
     * Primary partition key with auto-generation.
     * SDK v2: Uses custom @DynamoDBAutoGeneratedKey annotation for auto-generation support.
     */
    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /**
     * GSI partition key for idx_global_usrNo_feedOpenYn.
     */
    @DynamoDbSecondaryPartitionKey(indexNames = "idx_global_usrNo_feedOpenYn")
    @DynamoDbAttribute("usrNo")
    public int getUsrNo() {
        return usrNo;
    }

    public void setUsrNo(int usrNo) {
        this.usrNo = usrNo;
    }

    @DynamoDbAttribute("feedId")
    public String getFeedId() {
        return feedId;
    }

    public void setFeedId(String feedId) {
        this.feedId = feedId;
    }

    /**
     * Date attribute - SDK v2 stores as epoch milliseconds (Number type) by default.
     */
    @DynamoDbAttribute("feedRegDate")
    public Date getFeedRegDate() {
        return feedRegDate;
    }

    public void setFeedRegDate(Date feedRegDate) {
        this.feedRegDate = feedRegDate;
    }

    /**
     * GSI sort key for idx_global_usrNo_feedOpenYn.
     *
     * Important: DynamoDB GSI keys must be scalar types (B, N, or S).
     * Boolean BOOL type is not allowed as a GSI key.
     *
     * SDK v1: Used @DynamoDBTyped(DynamoDBAttributeType.N) to store as Number
     * SDK v2: Uses @DynamoDbConvertedBy(BooleanNumberAttributeConverter.class)
     *
     * The converter stores:
     * - true → "1" (Number)
     * - false → "0" (Number)
     *
     * This maintains backward compatibility with SDK v1 behavior where booleans
     * in GSI keys were stored as Numbers.
     */
    @DynamoDbSecondarySortKey(indexNames = "idx_global_usrNo_feedOpenYn")
    @DynamoDbAttribute("feedOpenYn")
    @DynamoDbConvertedBy(BooleanNumberAttributeConverter.class)
    public boolean isFeedOpenYn() {
        return feedOpenYn;
    }

    public void setFeedOpenYn(boolean feedOpenYn) {
        this.feedOpenYn = feedOpenYn;
    }
}
