package org.socialsignin.spring.data.dynamodb.domain.sample;

import org.socialsignin.spring.data.dynamodb.annotation.DynamoDBAutoGeneratedKey;
import org.springframework.data.annotation.Id;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbConvertedBy;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.nio.ByteBuffer;
import java.time.Instant;
import java.util.Set;

/**
 * Domain model demonstrating binary data and Set types in DynamoDB.
 * Tests ByteBuffer for binary data and various Set types.
 *
 * Table: FileMetadata
 * Primary Key: fileId (hash key)
 *
 * SDK v2 Migration Notes:
 * - ByteBuffer is supported natively in SDK v2 for binary data (B type)
 * - Set types (StringSet, NumberSet) are supported natively in SDK v2
 * - @DynamoDBAutoGeneratedKey is a custom annotation for SDK v1 compatibility mode
 */
@DynamoDbBean
public class FileMetadata {

    private String fileId;
    private String fileName;
    private Long fileSize;
    private ByteBuffer fileContent; // Binary data
    private ByteBuffer fileThumbnail; // Binary thumbnail
    private Set<String> tags; // StringSet
    private Set<String> permissions; // StringSet
    private Set<Integer> versionNumbers; // NumberSet
    private String contentType;
    private Instant uploadedAt;
    private String uploadedBy;

    @Id
    @DynamoDbPartitionKey
    @DynamoDbAttribute("fileId")
    @DynamoDBAutoGeneratedKey
    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    @DynamoDbAttribute("fileName")
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @DynamoDbAttribute("fileSize")
    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * Binary file content stored as ByteBuffer.
     * SDK v2 automatically handles ByteBuffer as binary data (B type).
     */
    @DynamoDbAttribute("fileContent")
    public ByteBuffer getFileContent() {
        return fileContent;
    }

    public void setFileContent(ByteBuffer fileContent) {
        this.fileContent = fileContent;
    }

    /**
     * Binary thumbnail stored as ByteBuffer.
     * SDK v2 automatically handles ByteBuffer as binary data (B type).
     */
    @DynamoDbAttribute("fileThumbnail")
    public ByteBuffer getFileThumbnail() {
        return fileThumbnail;
    }

    public void setFileThumbnail(ByteBuffer fileThumbnail) {
        this.fileThumbnail = fileThumbnail;
    }

    /**
     * Set of string tags (SS type in DynamoDB).
     * SDK v2 natively supports Set<String> for StringSet type.
     */
    @DynamoDbAttribute("tags")
    public Set<String> getTags() {
        return tags;
    }

    public void setTags(Set<String> tags) {
        this.tags = tags;
    }

    /**
     * Set of permission strings (SS type in DynamoDB).
     * SDK v2 natively supports Set<String> for StringSet type.
     */
    @DynamoDbAttribute("permissions")
    public Set<String> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<String> permissions) {
        this.permissions = permissions;
    }

    /**
     * Set of version numbers (NS type in DynamoDB).
     * SDK v2 natively supports Set<Integer> for NumberSet type.
     */
    @DynamoDbAttribute("versionNumbers")
    public Set<Integer> getVersionNumbers() {
        return versionNumbers;
    }

    public void setVersionNumbers(Set<Integer> versionNumbers) {
        this.versionNumbers = versionNumbers;
    }

    @DynamoDbAttribute("contentType")
    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    @DynamoDbAttribute("uploadedAt")
    @DynamoDbConvertedBy(InstantConverter.class)
    public Instant getUploadedAt() {
        return uploadedAt;
    }

    public void setUploadedAt(Instant uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    @DynamoDbAttribute("uploadedBy")
    public String getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }
}
