package org.socialsignin.spring.data.dynamodb.domain.sample;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.nio.ByteBuffer;
import java.time.Instant;
import java.util.Set;

/**
 * Domain model demonstrating binary data and Set types in DynamoDB.
 * Tests ByteBuffer for binary data and various Set types.
 *
 * Table: FileMetadata
 * Primary Key: fileId (hash key)
 */
@DynamoDBTable(tableName = "FileMetadata")
public class FileMetadata {

    private String fileId;
    private String fileName;
    private Long fileSize;
    private ByteBuffer fileContent; // Binary data
    private ByteBuffer fileThumbnail; // Binary thumbnail
    private Set<String> tags; // StringSet
    private Set<String> permissions; // StringSet
    private Set<Integer> versionNumbers; // NumberSet
    private String contentType;
    private Instant uploadedAt;
    private String uploadedBy;

    @Id
    @DynamoDBHashKey(attributeName = "fileId")
    @DynamoDBAutoGeneratedKey
    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    @DynamoDBAttribute(attributeName = "fileName")
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @DynamoDBAttribute(attributeName = "fileSize")
    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * Binary file content stored as ByteBuffer.
     * DynamoDB automatically handles binary data (B type).
     */
    @DynamoDBAttribute(attributeName = "fileContent")
    public ByteBuffer getFileContent() {
        return fileContent;
    }

    public void setFileContent(ByteBuffer fileContent) {
        this.fileContent = fileContent;
    }

    /**
     * Binary thumbnail stored as ByteBuffer.
     */
    @DynamoDBAttribute(attributeName = "fileThumbnail")
    public ByteBuffer getFileThumbnail() {
        return fileThumbnail;
    }

    public void setFileThumbnail(ByteBuffer fileThumbnail) {
        this.fileThumbnail = fileThumbnail;
    }

    /**
     * Set of string tags (SS type in DynamoDB).
     */
    @DynamoDBAttribute(attributeName = "tags")
    public Set<String> getTags() {
        return tags;
    }

    public void setTags(Set<String> tags) {
        this.tags = tags;
    }

    /**
     * Set of permission strings (SS type in DynamoDB).
     */
    @DynamoDBAttribute(attributeName = "permissions")
    public Set<String> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<String> permissions) {
        this.permissions = permissions;
    }

    /**
     * Set of version numbers (NS type in DynamoDB).
     */
    @DynamoDBAttribute(attributeName = "versionNumbers")
    public Set<Integer> getVersionNumbers() {
        return versionNumbers;
    }

    public void setVersionNumbers(Set<Integer> versionNumbers) {
        this.versionNumbers = versionNumbers;
    }

    @DynamoDBAttribute(attributeName = "contentType")
    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    @DynamoDBAttribute(attributeName = "uploadedAt")
    @DynamoDBTypeConverted(converter = InstantConverter.class)
    public Instant getUploadedAt() {
        return uploadedAt;
    }

    public void setUploadedAt(Instant uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    @DynamoDBAttribute(attributeName = "uploadedBy")
    public String getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy;
    }
}
