/*
 * Copyright © 2018 spring-data-dynamodb (https://github.com/prasanna0586/spring-data-dynamodb)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.socialsignin.spring.data.dynamodb.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for auto-generating timestamp values in SDK_V1_COMPATIBLE mode.
 *
 * <p>This annotation marks a field or getter method to have its value auto-generated
 * as a timestamp before saving to DynamoDB. Only works when {@link org.socialsignin.spring.data.dynamodb.core.MarshallingMode#SDK_V1_COMPATIBLE}
 * is configured.
 *
 * <p><b>SDK_V1_COMPATIBLE mode only:</b> This annotation is provided for backward compatibility
 * with AWS SDK v1's {@code @DynamoDBAutoGeneratedTimestamp}. SDK v2 does not have built-in
 * timestamp auto-generation support.
 *
 * <p><b>Supported field types:</b> {@code java.util.Date} or {@code Long}
 *
 * <p><b>Auto-generation behavior:</b>
 * <ul>
 * <li>Timestamp is generated only if the field is null</li>
 * <li>If you manually set a value, it won't be overwritten</li>
 * <li>{@link DynamoDBAutoGenerateStrategy#CREATE} - Generate on create only</li>
 * <li>{@link DynamoDBAutoGenerateStrategy#ALWAYS} - Generate on create and update</li>
 * </ul>
 *
 * <p><b>Example:</b>
 * <pre>
 * {@code @DynamoDbBean}
 * public class AuditLog {
 *     {@code @DynamoDbPartitionKey}
 *     private String logId;
 *
 *     {@code @DynamoDbAttribute}
 *     {@code @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)}
 *     private Date createdAt;
 *
 *     {@code @DynamoDbAttribute}
 *     {@code @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)}
 *     private Date modifiedAt;
 *
 *     // Getters and setters...
 * }
 * </pre>
 * @author Prasanna Kumar Ramachandran
 * @since 7.0.0
 * @see DynamoDBAutoGenerateStrategy
 * @see org.socialsignin.spring.data.dynamodb.core.AutoGeneratedKeyHelper
 * @see org.socialsignin.spring.data.dynamodb.core.MarshallingMode#SDK_V1_COMPATIBLE
 */
@Target({ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface DynamoDBAutoGeneratedTimestamp {
    /**
     * The strategy for when to generate the timestamp.
     * @return the auto-generation strategy
     */
    DynamoDBAutoGenerateStrategy strategy() default DynamoDBAutoGenerateStrategy.ALWAYS;
}
