/**
 * Copyright © 2018 spring-data-dynamodb (https://github.com/prasanna0586/spring-data-dynamodb)
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 *     http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.socialsignin.spring.data.dynamodb.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation for auto-generating key values in SDK_V1_COMPATIBLE mode.
 *
 * <p>This annotation marks a field or getter method to have its value auto-generated
 * as a UUID string before saving to DynamoDB. Only works when {@link org.socialsignin.spring.data.dynamodb.core.MarshallingMode#SDK_V1_COMPATIBLE}
 * is configured.
 *
 * <p><b>SDK_V1_COMPATIBLE mode only:</b> This annotation is provided for backward compatibility
 * with AWS SDK v1's {@code @DynamoDBAutoGeneratedKey}. New projects using SDK_V2_NATIVE mode
 * should use AWS SDK v2's {@code @DynamoDbAutoGeneratedUuid} with {@code AutoGeneratedUuidExtension}.
 *
 * <p><b>Supported field types:</b> String only
 *
 * <p><b>Auto-generation behavior:</b>
 * <ul>
 * <li>UUID is generated only if the field is null or empty string</li>
 * <li>If you manually set a value, it won't be overwritten</li>
 * <li>Works for both single save() and batchSave() operations</li>
 * </ul>
 *
 * <p><b>Example:</b>
 * <pre>
 * {@code @DynamoDbBean}
 * public class User {
 *     {@code @DynamoDbPartitionKey}
 *     {@code @DynamoDBAutoGeneratedKey}
 *     private String userId;
 *
 *     // Getters and setters...
 * }
 * </pre>
 * @author Prasanna Kumar Ramachandran
 * @since 7.0.0
 * @see org.socialsignin.spring.data.dynamodb.core.AutoGeneratedKeyHelper
 * @see org.socialsignin.spring.data.dynamodb.core.MarshallingMode#SDK_V1_COMPATIBLE
 */
@Target({ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface DynamoDBAutoGeneratedKey {
}
