/**
 * Copyright © 2018 spring-data-dynamodb (https://github.com/prasanna0586/spring-data-dynamodb)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.socialsignin.spring.data.dynamodb.annotation;

/**
 * Strategy for auto-generating timestamp values in SDK_V1_COMPATIBLE mode.
 *
 * <p>Used with {@link DynamoDBAutoGeneratedTimestamp} to control when timestamps
 * are automatically generated.
 *
 * @author Michael Lavelle
 * @author Sebastian Just
 * @since 7.0.0
 * @see DynamoDBAutoGeneratedTimestamp
 */
public enum DynamoDBAutoGenerateStrategy {
    /**
     * Generate timestamp on entity creation only.
     * The value will not be updated on subsequent saves.
     */
    CREATE,

    /**
     * Generate timestamp on both entity creation and updates.
     * The value will be updated every time the entity is saved.
     */
    ALWAYS
}
